Homework9:Aleksandr Voschilo
AlekseyQty/qap09-onl pull request #100
Opened 2022-08-21 16:43 UTC by writeln2012

2022-09-06 10:14 UTC, AlekseyQty requested changes
Нужно отрефакторить первое задание

2022-09-06 10:14 UTC, AlekseyQty commented on voshchilo_aleksandr_mihajlovich/hw_9/hw_9.py
> +            print(f"{the_book.name} is unavailable!")
Стоит брать книгу только есл она не зарезервирована. Сейчас ты берешь книгу, а потом проверяешь зарезервирована ли она

2022-09-06 10:14 UTC, AlekseyQty commented on voshchilo_aleksandr_mihajlovich/hw_9/hw_9.py
> +        self.the_book = the_book
Для чего ты используешь новую переменную внутри класса the_book? Можно сразу обратиться к полю класса book с помощью конструкции the_book.reserved = False

2022-09-13 14:42 UTC, writeln2012 commented on voshchilo_aleksandr_mihajlovich/hw_9/hw_9.py
> +            print(f"{the_book.name} is unavailable!")
Исправил

2022-09-13 14:42 UTC, writeln2012 commented on voshchilo_aleksandr_mihajlovich/hw_9/hw_9.py
> +        self.the_book = the_book
Исправил

2022-09-13 14:42 UTC, writeln2012 commented
Исправил

2022-10-10 18:42 UTC, merged