Add files to "Homework 3"
AlekseyQty/qap09-onl pull request #17
Opened 2022-07-22 15:48 UTC by ShulgaDmitry

Sending homework 3

2022-07-22 15:50 UTC, ShulgaDmitry commented
Sending homework 3

2022-07-23 12:02 UTC, AlekseyQty requested changes

2022-07-23 12:02 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_3/task_3_3.py
> +print(f' Reverse "Ivanou Ivan" - "{string[7:] + " " + string[:6]}"')
Задание выполнено правильно, но лучше избегать решений, которые так сильно завязаны на последовательности символов в строке. 

Такие решения называют захардкоженными, и если есть возможность, их лучше избегать т.к мы никогда не знаем когда придется масштабировать нашу программу и чем больше в ней будет хардкода, тем больнее в дальнейшем будет его менять.

Если мы захотим модифицировать наш код чтобы он универсально мог менять местами имя и фамилию, то для каждой новой пары придется менять код для коррректного извлечения среза.

Подумай над тем, как можно сделать тоже самое, но для любой комбинации Имя + Фамилия (не нужно писать именно функцию для этого, просто модифицируй код внутри f строки в print

2022-07-23 17:24 UTC, ShulgaDmitry commented
Fixed homework3

2022-07-25 10:33 UTC, merged