Homework3 Tanya Shevchuk
AlekseyQty/qap09-onl pull request #19
Opened 2022-07-22 17:33 UTC by TatyanaShevchuk

add new branch "hm3" and 4 files with tasks

2022-07-23 12:09 UTC, AlekseyQty requested changes

2022-07-23 12:09 UTC, AlekseyQty commented on shevchuk_tatyana_aleksandrovna/hm3/task_3_3.py
> +print(f'Ivanou Ivan - {surname_name[7:] + " " + surname_name[:6]}')
Задание выполнено правильно, но лучше избегать решений, которые так сильно завязаны на последовательности символов в строке.

Такие решения называют захардкоженными, и если есть возможность, их лучше избегать т.к мы никогда не знаем когда придется масштабировать нашу программу и чем больше в ней будет хардкода, тем больнее в дальнейшем будет его менять.

Если мы захотим модифицировать наш код чтобы он универсально мог менять местами имя и фамилию, то для каждой новой пары придется менять код для коррректного извлечения среза.

Подумай над тем, как можно сделать тоже самое, но для любой комбинации Имя + Фамилия (не нужно писать именно функцию для этого, просто модифицируй код внутри f строки в print

2022-07-23 12:09 UTC, AlekseyQty commented on shevchuk_tatyana_aleksandrovna/hm3/task_3_4.py
> +print(f'{string[1:8]}')
Тут тоже самое что и в задании 3, попробуй написать код, который будет работать в любом случае.

Если мы изменим ввод, то все сломается.

2022-07-25 20:58 UTC, TatyanaShevchuk commented
изменила 2 файла.  почему-то добавился файл с сегоднящнего занятия, но пустой. как его можно удалить?

2022-07-28 10:14 UTC, AlekseyQty commented
> изменила 2 файла. почему-то добавился файл с сегоднящнего занятия, но пустой. как его можно удалить?

Можешь удалить у себя файл локально и сделать новый коммит, и запушить его

2022-07-29 13:50 UTC, TatyanaShevchuk commented
так и не поняла как это слелать через git и удалила просто тут

2022-07-31 09:23 UTC, merged