Aleksandr Voschilo, Homework3
AlekseyQty/qap09-onl pull request #20
Opened 2022-07-23 09:43 UTC by writeln2012

2022-07-23 12:14 UTC, AlekseyQty requested changes

2022-07-23 12:14 UTC, AlekseyQty commented on voshchilo_aleksandr_mihajlovich/hw_3/hw_3.py
> +print(" ".join(String_3.split()[::-1]))
Красиво сделано!

2022-07-23 12:14 UTC, AlekseyQty commented on voshchilo_aleksandr_mihajlovich/hw_3/hw_3.py
> +String_1 = "www.my_site.com#about"
К решению заданий никаких претензий нет - все отлично.

Переменные должны быть названы в формате snake_case: https://peps.python.org/pep-0008/#function-and-variable-names

Переделай названия переменных на стиль, соответствующий PEP-8

2022-07-24 07:19 UTC, writeln2012 commented on voshchilo_aleksandr_mihajlovich/hw_3/hw_3.py
> +String_1 = "www.my_site.com#about"
Исправил

2022-07-24 07:45 UTC, writeln2012 commented on voshchilo_aleksandr_mihajlovich/hw_3/hw_3.py
> +print(" ".join(String_3.split()[::-1]))
Если кому-то из ребят будет интересно как она получилась:

case_4 = "Ivan Ivanou"
name = case_4.split()
name_2 = name[::-1]
name_3 = ' '.join(name_2)

2022-07-25 10:35 UTC, merged