Homework 3: Denis Fadeev
AlekseyQty/qap09-onl pull request #31
Opened 2022-07-26 15:38 UTC by xSmugxJoex

2022-07-28 10:40 UTC, AlekseyQty requested changes
1. Нужно вернуть файл из второй домашки в ветку
2. Нужно исправить 1 и 3 задание

2022-07-28 10:40 UTC, AlekseyQty commented on fadeev_denis_olegovich/hm_2/denis_fadeev.py
> -print("Hello word!")
Зачем ты удалил файл из второй домашки в пулл реквесте к третей домашке? 

Если ты удаляешь какой-то файл и делаешь коммит + пуш, то гит считает это как изменение. Сделав это в другой ветке, а потом сделав пулл реквест этой ветки в мастер ты запрашиваешь изменения мастера на основе твоей текущей ветки. То есть в мастере тоже удалится файл после того как я вмержу пулл реквест. 

Нужно вернуть файл в текущую ветку

2022-07-28 10:40 UTC, AlekseyQty commented on fadeev_denis_olegovich/hm_3/homework_3_1.py
> +print(site[:15] + character_replacement + site[15+1:])
Задание выполнено правильно, но лучше избегать решений, которые так сильно завязаны на последовательности символов в строке.

Такие решения называют захардкоженными, и если есть возможность, их лучше избегать т.к мы никогда не знаем когда придется масштабировать нашу программу и чем больше в ней будет хардкода, тем больнее в дальнейшем будет его менять.

Если мы захотим модифицировать наш код чтобы он универсально мог заменять символ в строке, то для каждой новой строки придется менять код для коррректного извлечения среза.

Подумай над тем, как можно сделать тоже самое, но для любой строки, содержащей символ #

2022-07-28 10:40 UTC, AlekseyQty commented on fadeev_denis_olegovich/hm_3/homework_3_3.py
> +print(name[7:], name[:7])
Такое же замечание, как и к первому заданию.  Попробуй сделать универсальное решение, которое будет менять местами любые Имя + фамилия

2022-07-31 11:27 UTC, xSmugxJoex commented on fadeev_denis_olegovich/hm_2/denis_fadeev.py
> -print("Hello word!")
Выполнено.

2022-07-31 11:27 UTC, xSmugxJoex commented on fadeev_denis_olegovich/hm_3/homework_3_1.py
> +print(site[:15] + character_replacement + site[15+1:])
Выполнено.

2022-07-31 11:28 UTC, xSmugxJoex commented on fadeev_denis_olegovich/hm_3/homework_3_3.py
> +print(name[7:], name[:7])
Выполнено.

2022-07-31 11:37 UTC, merged