Homework5
AlekseyQty/qap09-onl pull request #42
Opened 2022-07-29 11:47 UTC by ShulgaDmitry

2022-07-31 11:05 UTC, AlekseyQty requested changes
Нужно исправить 3 задание

2022-07-31 11:05 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_5/task_5_3.py
> +        for i in range(1, len(number)):
Результатом range(1, len(number)) будет последовательность (1,2,3). То есть ты теряешь 0 индекс списка. 

Для того чтобы пройтись по всему списко нужно использовать range(len(number))

2022-07-31 11:05 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_5/task_5_3.py
> +                count_1 = "Одна корова"
Зачем каждый раз приводить count к строке и сразу же перезаписывать переменную? Выражение count_1 = str(count) не имеет смысла т.к каждый раз сразу же перезаписывается следующей строкой

2022-07-31 11:05 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_5/task_5_3.py
> +    number = input("Please enter hidden four-digit number: ")
После каждой неудачной попытки мы будем заного вводить последовательность, которую нужно отгадать. Это число должно быть сгенерировано один раз за игру.

Лучше сгенерируй его до while с помощью random.randint()

2022-07-31 11:05 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_5/task_5_3.py
> +        print(f"{count_1}, {count_3} ")
Если ни одно из чисел не будет угадано, то программа упадет на этом месте т.к переменные count_1 и count_3 объявляются только при условии что одно из чисел угадано правильно

2022-07-31 11:05 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_5/task_5_3.py
> +            if count_2 == 1:
Если мы угадали позицию числа и само число, то в ответе получим одновременно и быка и корову. Игра должна работать по-другому, если мы угадали и число и его позицию, то пишем только про быка. Если же угадали только число, то пишем корову.  

Пример:

Задумано тайное число «3219».

Попытка: «2310».

Результат: две «коровы» (две цифры: «2» и «3» — угаданы на неверных позициях) и один «бык» (одна цифра «1» угадана вплоть до позиции).

То есть цифра 1 не идет одновременно в плюс к коровам и быкам, а только к быкам

2022-08-01 06:25 UTC, ShulgaDmitry commented on shulga_dmitrij_vladimirovich/hm_5/task_5_3.py
> +                count_1 = "Одна корова"
У меня появляется ошибка, если я так не делаю (Traceback (most recent call last):
  File "D:\pythonProject\QAP09-onl\qap09-onl\shulga_dmitrij_vladimirovich\hm_5\task_5_3.py", line 23, in <module>
    count += 1
TypeError: can only concatenate str (not "int") to str)

2022-08-01 09:50 UTC, ShulgaDmitry commented
Внес все изменения

2022-08-02 23:34 UTC, AlekseyQty requested changes
Нужно исправить 3 задание.

Сейчас программа работает неправильно

2022-08-02 23:34 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_5/task_5_3.py
> +            if count_2 == 2:
У тебя два условия if count_2 == 2, одно нужно убрать

2022-08-02 23:34 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_5/task_5_3.py
> +            if count_2 == 2:
Лучше использовать конструкцию if-elif-else, т.к если ты попал в один из if последующие нет смылса проверять

2022-08-02 23:34 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_5/task_5_3.py
> +                    count += 1
Из-за этой строчки в программе есть баг. 

Попробуй в загаданном числе написать 2 цифры на своем месте и 2 не на своем. Например для числа 1234 попробуй в ответе написать 1243, в выводе программы будет:

Please enter your four-digit number: 1243
Три коровы Два быка

2022-08-02 23:34 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_5/task_5_3.py
> +                index = None
Лучше объявить эти переменные до цикла for, т.к при успешном условии они перезапишутся корректными. Сейчас есть ситуации когда эти переменные могут быть не объявлены

2022-08-02 23:34 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_5/task_5_3.py
> +            print(f"{count_1} {count_3}")
Сейчас при отсутствии быков/коров в выводе будет писаться "None", типо такого:

Четыри коровы None

Нужно либо ничего не выводить вместо None, либо выводить 0

2022-08-03 06:31 UTC, ShulgaDmitry commented on shulga_dmitrij_vladimirovich/hm_5/task_5_3.py
> +                    count += 1
Подправил логику

2022-08-03 06:32 UTC, ShulgaDmitry commented on shulga_dmitrij_vladimirovich/hm_5/task_5_3.py
> +            if count_2 == 2:
Удалил, случайно продублировал

2022-08-03 06:33 UTC, ShulgaDmitry commented on shulga_dmitrij_vladimirovich/hm_5/task_5_3.py
> +            if count_2 == 2:
Это место подправил

2022-08-11 10:34 UTC, merged