Homework4: Mariya Bilaya
AlekseyQty/qap09-onl pull request #43
Opened 2022-07-29 18:22 UTC by MaryBilaya

Add homework_4 from exercise 1 to  exercise 4

2022-07-31 10:15 UTC, AlekseyQty requested changes
С 4 домашкой все ок. Нужно синхронизировать файлы в текущей ветке с файлами из 3 домашки

2022-07-31 10:15 UTC, AlekseyQty commented on bilaya_mariya_nikolaevna/hm_3/Mariya_Bilaya.py
> +# Exercise_1. Заменить символ "#" на символ "/" в строке 'www.my_site.com#about'.
Нужно синхронизировать состояние файлов из 4 домашки с файлами из 3 домашки

Сейчас у тебя получается ситуация, что ты сделала ветку на основе той, которая еще не вмержена в мастер. При этом в ветке с 3 домашкой перед мержем в мастер были сделаны изменяния. Из-за того что файлы в текущей домашке отличаются от файлов в пулл реквесте с 3 домашкой при попытке мержа пулл реквеста будет merge conflict, т.е мне нужно будет определить какая из версий правильная. 

У тебя есть несколько вариантов как избегать таких проблем:
1. Делать ветку с новым кодом только на основании ветки, которая уже находится в мастере
2. Перед созданием пулл реквеста обновить состояние файлов в текущей ветке до состояния мастера
3. Можно не индексировать файлы, которые не относятся к текущей домашке при коммитах в новую ветку

2022-07-31 10:15 UTC, AlekseyQty commented on bilaya_mariya_nikolaevna/hm_3/practise_hm_3.py
> +# Exercise_1. Переменной var_int присвойте значение 10, var_float - значение 8.4, var_str - "No".
Этот файл тоже нужно актуализировать до состояние мастера 3 домашки

2022-07-31 15:46 UTC, MaryBilaya commented on bilaya_mariya_nikolaevna/hm_3/practise_hm_3.py
> +# Exercise_1. Переменной var_int присвойте значение 10, var_float - значение 8.4, var_str - "No".
Привет, Леша. Не совсем поняла, как мне сделать синхронизацию. Можешь подсказать или уже на занятии завтра расскажешь

И как поступать в случае, например: я сделала pull request 3 домашки, к моменту как я начинаю делать 4, ты еще не сделал merge третьей в main. На основании чего мне создавать ветку Homework4?

2022-08-02 09:59 UTC, AlekseyQty commented on bilaya_mariya_nikolaevna/hm_3/practise_hm_3.py
> +# Exercise_1. Переменной var_int присвойте значение 10, var_float - значение 8.4, var_str - "No".
Как и договорились на занятии текущие пулл реквесты я вмержу сам, так что замечание неактуально

2022-08-02 09:59 UTC, merged