Add the 5th homework
AlekseyQty/qap09-onl pull request #45
Opened 2022-07-30 06:12 UTC by Malashko17

Add the 5th homework

2022-07-31 11:32 UTC, AlekseyQty requested changes
Очень интересное решение, классная работа с числами. 

Нужно немного допилить логику игры в 3 задании

2022-07-31 11:32 UTC, AlekseyQty commented on malashko_pavel_yurevich/hw_5/task_5_3.py
> +    print(f"{len(set(system_number_list) & set(user_number_list))} Коровы и {counter} бык")
Логика игры немного другая:

Если мы угадали и число и его позицию, то пишем только про быка. Если же угадали только число, то пишем корову.

Пример:

Задумано тайное число «3219».

Попытка: «2310».

Результат: две «коровы» (две цифры: «2» и «3» — угаданы на неверных позициях) и один «бык» (одна цифра «1» угадана вплоть до позиции).

То есть цифра 1 не идет одновременно в плюс к коровам и быкам, а только к быкам

2022-07-31 15:12 UTC, Malashko17 commented on malashko_pavel_yurevich/hw_5/task_5_3.py
> +    print(f"{len(set(system_number_list) & set(user_number_list))} Коровы и {counter} бык")
Да, немного недочитал условие, в итоге просто отнял быков от коров и перенес немного вывод этого сообщения.

2022-08-02 09:48 UTC, AlekseyQty approved these changes

2022-08-02 09:49 UTC, merged