Amelchenko/hw4
AlekseyQty/qap09-onl pull request #46
Opened 2022-07-30 15:36 UTC by AmelchenkoDima

2022-07-31 10:22 UTC, AlekseyQty requested changes
Нужно исправить форматирование файла и 5 задание

2022-07-31 10:22 UTC, AlekseyQty commented on amelchenko_dmitrij_olegovich/hw4/hw_4.py
> +sotr_dict = sorted(list(set(app_dict)))
Переменная app_dict у тебя не объявлена, наверное имелось ввиду uni_dict?

2022-07-31 10:22 UTC, AlekseyQty commented on amelchenko_dmitrij_olegovich/hw4/hw_4.py
> +a = { 'a': 1, 'b': 2, 'c': 3}
Есть много моментов по форматированию, которые не соответствуют PEP-8. 

В pycharm есть автоматическое форматирование кода. Советую сначала попробовать пофиксить все синтаксические неточности самому, а в дальнейшем уже использовать пайчармовскую утилиту.

https://www.jetbrains.com/help/pycharm/reformat-file-dialog.html

2022-07-31 13:57 UTC, AmelchenkoDima commented on amelchenko_dmitrij_olegovich/hw4/hw_4.py
> +a = { 'a': 1, 'b': 2, 'c': 3}
Исправил

2022-07-31 13:57 UTC, AmelchenkoDima commented on amelchenko_dmitrij_olegovich/hw4/hw_4.py
> +sotr_dict = sorted(list(set(app_dict)))
Исправил

2022-08-02 09:44 UTC, AlekseyQty approved these changes

2022-08-02 09:44 UTC, merged