Homework5:Aleksandr Voschilo
AlekseyQty/qap09-onl pull request #50
Opened 2022-07-31 18:46 UTC by writeln2012

2022-08-02 10:38 UTC, AlekseyQty requested changes
Нужно исправить замечания

2022-08-02 10:38 UTC, AlekseyQty commented on voshchilo_aleksandr_mihajlovich/hw_5/hw_5.py
> +# print(list_number)
Нужно убрать отладочный код из ПРа

2022-08-02 10:38 UTC, AlekseyQty commented on voshchilo_aleksandr_mihajlovich/hw_5/hw_5.py
> +number_f = math.prod(list_number)
В задаче нужно написать свой метод расчета факториала с использованием цикла. Библиотечные методы не подходят

2022-08-02 10:38 UTC, AlekseyQty commented on voshchilo_aleksandr_mihajlovich/hw_5/hw_5.py
> +    a = "1"
Лучше сразу присвоить a = str(input("Введите четырехзначное число без повторов: ")), если пользователь введет неправильные данные, то мы перезапишем переменную уже в новом цикле.

Также стоит дать переменной "a" какое-то осмысленное имя, например user_input

2022-08-02 10:38 UTC, AlekseyQty commented on voshchilo_aleksandr_mihajlovich/hw_5/hw_5.py
> +    while len(set(list(map(int, a)))) < 4:  # проверка числа на повтор
Лучше сделать проверку !=4, т.к под твое условие подходят все числа с длинной больше 4. На же устраивает только 4

2022-08-02 10:38 UTC, AlekseyQty commented on voshchilo_aleksandr_mihajlovich/hw_5/hw_5.py
> +list_b = []
Стоит осмысленно назвать переменную. Например, secret_number

2022-08-02 10:38 UTC, AlekseyQty commented on voshchilo_aleksandr_mihajlovich/hw_5/hw_5.py
> +            print("Четыре коровы")
Такое решение работает, но оно очень громосткое и плохо масштабируется. Например, если мы захотим сделать игру с 5 символами, то придется менять кучу кода.

Все это можно заменить одной строчкой: 
`print(f"{result_list.count('Корова')} коров(а/ы) {result_list.count('Бык')} бык(а)")`

Выглядит чуть менее красиво с точки зрения пользователя, зато для разработчика намного удобнее

2022-08-02 10:38 UTC, AlekseyQty commented on voshchilo_aleksandr_mihajlovich/hw_5/hw_5.py
> +    # print(result_list)
Все закоментированные print нужно убрать из пулл реквеста

2022-08-04 10:48 UTC, writeln2012 commented on voshchilo_aleksandr_mihajlovich/hw_5/hw_5.py
> +            print("Четыре коровы")
Я слишком буквально принял пример из домашнего задания (Пример
Загадано число 3219
>>> 2310
Две коровы, один бык
>>> 3219
Вы выиграли!)

Думал вывод должен быть именно строками да еще и со сменой окончаний) Рад что можно сделать проще))

2022-08-04 11:06 UTC, writeln2012 commented on voshchilo_aleksandr_mihajlovich/hw_5/hw_5.py
> +# print(list_number)
Исправил

2022-08-04 11:06 UTC, writeln2012 commented on voshchilo_aleksandr_mihajlovich/hw_5/hw_5.py
> +number_f = math.prod(list_number)
Исправил

2022-08-04 11:06 UTC, writeln2012 commented on voshchilo_aleksandr_mihajlovich/hw_5/hw_5.py
> +    a = "1"
Исправил

2022-08-04 11:06 UTC, writeln2012 commented on voshchilo_aleksandr_mihajlovich/hw_5/hw_5.py
> +    while len(set(list(map(int, a)))) < 4:  # проверка числа на повтор
Исправил

2022-08-04 11:06 UTC, writeln2012 commented on voshchilo_aleksandr_mihajlovich/hw_5/hw_5.py
> +list_b = []
Исправил

2022-08-04 11:07 UTC, writeln2012 commented on voshchilo_aleksandr_mihajlovich/hw_5/hw_5.py
> +    # print(result_list)
Исправил

2022-08-15 14:57 UTC, merged