Homework 6: Maksim Vajda
AlekseyQty/qap09-onl pull request #58
Opened 2022-08-03 19:30 UTC by metalveor

Add Homework 6 task 3: Calculator

2022-08-16 11:17 UTC, AlekseyQty requested changes
Нужно исправить 3 задание

2022-08-16 11:17 UTC, AlekseyQty commented on vajda_maksim_valerevich/hm_6/homework_6_3.py
> +    return (f'Результат вашей операции: {result}')
Переменная result может быть не определена.

Если ты вызовешь функцию, не проверив перед этим что calc_start в диапазоне, который ты ждешь, то программа свалится.

Лучше всегда перед использованием переменной в логических блоках объявляй ее с каким-то значением по-умолчанию

2022-08-16 11:17 UTC, AlekseyQty commented on vajda_maksim_valerevich/hm_6/homework_6_3.py
> +    if calc_start == 1:
Плохо что твоя функция завязана на глобальную переменную. 

Функции стоит стараться писать так, чтобы они могли работать независимо от глобальных переменных.

Тут можно просто добавить дополнительный аргумент calc_option в функцию и прокидывать его при вызове из основной ветки программы

2022-08-16 11:28 UTC, metalveor commented on vajda_maksim_valerevich/hm_6/homework_6_3.py
> +    return (f'Результат вашей операции: {result}')
Если правильно понял ошибку, то я проверяю переменную calc_start перед началом блока функции калькулятора. 
If calc_start > 4:
    ...

2022-08-16 20:01 UTC, metalveor commented
Исправил.
Если правильно понял допущенные ошибки.

2022-08-21 19:51 UTC, AlekseyQty commented
> Исправил. Если правильно понял допущенные ошибки.

Я не совсем это имел ввиду. Сейчас твоя функция calculator завязана на параметр calc_start, который не является частью функции.

Стоит внести его в аргумент функции и вызывать вместе с ней.

2022-08-21 19:52 UTC, AlekseyQty commented on vajda_maksim_valerevich/hm_6/homework_6_3.py
> +    if calc_start == 1:
Нужно добавить в функцию calculator аргумент calc_start

2022-08-22 14:40 UTC, metalveor commented
Исправил 2.0

2022-08-23 14:09 UTC, merged