homework5
AlekseyQty/qap09-onl pull request #68
Opened 2022-08-08 11:05 UTC by Boristalataj

2022-08-21 19:33 UTC, AlekseyQty requested changes
Нужно исправить 3 задание

2022-08-21 19:33 UTC, AlekseyQty commented on talataj_boris_gennadevich/homework5/homework5.py
> +    if list_number2.count(i) == 1:
Если написать число 3714 должно быть 2 быка 2 коровы, сейчас у тебя:

Введите 4-х значное число:3714
количство коров:  4
количество быков:  2

2022-08-21 19:33 UTC, AlekseyQty commented on talataj_boris_gennadevich/homework5/homework5.py
> +
Игра должна давать ввести пользователю число пока он не угадает правильный ответ. Сейчас у тебя программа завершается после одного ввода

2022-08-22 19:54 UTC, Boristalataj commented on talataj_boris_gennadevich/homework5/homework5.py
> +    if list_number2.count(i) == 1:
сколько цифр угадано без совпадения с их позициями в тайном числе
# (то есть количество коров)

2022-09-06 10:20 UTC, merged