Homework 7: Maksim Vajda
AlekseyQty/qap09-onl pull request #72
Opened 2022-08-09 16:20 UTC by metalveor

Added homework_7, tasks 2 and 3.

2022-09-04 19:25 UTC, AlekseyQty requested changes
Нужно поправить шифр цезаря

2022-09-04 19:25 UTC, AlekseyQty commented on vajda_maksim_valerevich/hm_7/homework_7_3.py
> +def encode(text_encrypt,key_crypt):
В алгоритме есть ошибка.

Попробуй зашифровать строку "asd" со сдвигом 8.

В результате станет 2 символа, вместо 3-ех

Также попробуй сначала зашифровать что-то своим алгоритмом, а потом расшифровать. По-идее должно получиться одно и тоже

2022-09-04 20:14 UTC, metalveor commented on vajda_maksim_valerevich/hm_7/homework_7_3.py
> +def encode(text_encrypt,key_crypt):
С примерами из условия и примерами, что сам придумывал работало. С asd + 8 действительно не работает. Так и не смог найти причину. Нужна помощь

2022-09-06 14:14 UTC, AlekseyQty reviewed
Добавил комментарий по багу, попробуй разобраться

2022-09-06 14:14 UTC, AlekseyQty commented on vajda_maksim_valerevich/hm_7/homework_7_3.py
> +                    result.append(key_dict[(symbol - key_crypt) % len(key_dict)])
Два вот этих куска можно объединить в одно условие else. Условие result.append(key_dict[(1 + symbol + key_crypt) % len(key_dict) + 1]) вообще не работает.

Баг с 'asd' был потому что ты не проверял условие когда symbol - key_crypt == len(key_dict), т.е возможные у тебя варианты были только меньше, больше, и меньше нуля

2022-09-07 17:19 UTC, metalveor commented on vajda_maksim_valerevich/hm_7/homework_7_3.py
> +                    result.append(key_dict[(symbol - key_crypt) % len(key_dict)])
Fixed

2022-10-10 18:10 UTC, merged