Homework 7: Dmitry Shulga
AlekseyQty/qap09-onl pull request #77
Opened 2022-08-11 18:19 UTC by ShulgaDmitry

2022-08-22 07:48 UTC, AlekseyQty requested changes
Нужно отрефакторить 1 и 3 задание и переделать 2

2022-08-22 07:48 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_7/task_7_1.py
> +        # changed_matrix(number_line, number_column)
Нужно убрать лишние комментарии из пулл реквеста, в продуктовый код не должны попадать лишние строки кода.

2022-08-22 07:48 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_7/task_7_1.py
> +            #print("]")
Лучше определи функцию вне основного кода программы. 

Сейчас в этой функции нет особого смысла, т.к ты не сможешь ее переиспользовать в других местах твоей программы.

Такие функции имеет смысл объявлять если ты собираешься их использовать в очень специфичном месте и они будут переиспользованы несколько раз

2022-08-22 07:48 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_7/task_7_2.py
> +        positive_numbers.append(i)
Этот цикл не является генератором.

Генератор должен отдавать по одному элементу с помощью yield

2022-08-22 07:48 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_7/task_7_3.py
> +        encode_word.append(j)
Для копирования списка лучше используй list.copy() или 
encode_word = my_word[::]

2022-08-22 07:48 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_7/task_7_3.py
> +        def encode(encode_word):
Нужно вынести определение функции из ветвления в основную ветку программы.

Сейчас в функции нет смысла, ты мог просто использовать код написанный внутри нее без объявления функции.

Из-за того что функция объявляется не всегда ее не удастся переиспользовать в дргуих частях программы

2022-08-23 17:13 UTC, ShulgaDmitry commented
Вроде все поправил, про функции тоже все понял, но ошибка возможно еще в следующих домашках будет встречаться, которые я сделал прежде чем узнал об ошибке

2022-09-06 10:25 UTC, merged