Homework7:Aleksandr Voschilo
AlekseyQty/qap09-onl pull request #81
Opened 2022-08-14 19:12 UTC by writeln2012

2022-08-15 16:23 UTC, writeln2012 commented on voshchilo_aleksandr_mihajlovich/hw_7/hw_7.py
> +    message = str(input("Введите текст для шифрования: "))
для ДЕшифрования

2022-09-06 08:31 UTC, AlekseyQty requested changes
Нужно исправить небольшую ошибку в шифре цезаря.

В остальном задание сделано отлично

2022-09-06 08:31 UTC, AlekseyQty commented on voshchilo_aleksandr_mihajlovich/hw_7/hw_7.py
> +            new_message_translate.append(list_alf_letters[i])
Тут ты будешь пытаться обратиться по индексу, который является строкой.

Т.е например list_alf_letters['1']. 

Нужно привести строку к числу перед обращением по индексу

2022-09-10 07:11 UTC, writeln2012 commented on voshchilo_aleksandr_mihajlovich/hw_7/hw_7.py
> +            new_message_translate.append(list_alf_letters[i])
list_alf_letters у меня не строка, а список из символов латинского алфавита. По индексу я обращаюсь к списку, а не строке.

2022-09-18 14:27 UTC, writeln2012 commented on voshchilo_aleksandr_mihajlovich/hw_7/hw_7.py
> +            new_message_translate.append(list_alf_letters[i])
Вроде не ошибка, или я не понимаю

2022-10-10 18:17 UTC, AlekseyQty commented on voshchilo_aleksandr_mihajlovich/hw_7/hw_7.py
> +            new_message_translate.append(list_alf_letters[i])
Да, действительно, ошибкой не является.

Я изначально неправильно понял код.

2022-10-10 18:17 UTC, merged