Homework7: Mariya Bilaya
AlekseyQty/qap09-onl pull request #83
Opened 2022-08-14 22:10 UTC by MaryBilaya

Add hm_7 without exercise 1

2022-09-04 19:13 UTC, AlekseyQty requested changes
Нужно поправить шифр цезаря.

Остальные задания сделаны отлично

2022-09-04 19:13 UTC, AlekseyQty commented on bilaya_mariya_nikolaevna/hm_7/Mariya_Bilaya_7.py
> +            encode_text += alphabet[new_index]
У тебя нет проверки на выход за границу массива.

Например если кодируем букву 'u' и делаем смещение на 10 символов то получим ошибку: IndexError: string index out of range

2022-09-08 11:30 UTC, MaryBilaya commented on bilaya_mariya_nikolaevna/hm_7/Mariya_Bilaya_7.py
> +            encode_text += alphabet[new_index]
Расширила границы алфавита. Спасибо за обратную связь

2022-10-10 18:19 UTC, merged

2022-10-10 18:22 UTC, MaryBilaya commented
Леша, привет. Подскажи, вылетело с головы что 10 домашку не доделала. Могу
ли я на днях постараться доделать и прислать на github?

вс, 4 сент. 2022 г. в 22:13, Aleksey ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Нужно поправить шифр цезаря.
>
> Остальные задания сделаны отлично
> ------------------------------
>
> In bilaya_mariya_nikolaevna/hm_7/Mariya_Bilaya_7.py
> <https://github.com/AlekseyQty/qap09-onl/pull/83#discussion_r962357175>:
>
> > +print(("-") * 25 + "Сaesar_Сipher" + ("-") * 25)
>
> +
>
> +while True:
>
> +    print("Enter 0 to stop the program")
>
> +    alphabet = "abcdefghijklmnopqrstuvwxyz"
>
> +    my_text = input("Enter you text for coding: ")
>
> +    if my_text == "0":
>
> +        break
>
> +    shift = int(input("Enter a shift (number from 1 to 25): "))
>
> +    my_text = my_text.lower()
>
> +    encode_text = " "
>
> +    for letter in my_text:
>
> +        index = alphabet.find(letter)
>
> +        new_index = index + shift
>
> +        if letter in alphabet:
>
> +            encode_text += alphabet[new_index]
>
>
> У тебя нет проверки на выход за границу массива.
>
> Например если кодируем букву 'u' и делаем смещение на 10 символов то
> получим ошибку: IndexError: string index out of range
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AlekseyQty/qap09-onl/pull/83#pullrequestreview-1095704714>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2ELZCNIATYTQHRSTC6FSL3V4TYHFANCNFSM56QRC6XA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>