Homework 8: Dmitry Shulga
AlekseyQty/qap09-onl pull request #85
Opened 2022-08-15 12:38 UTC by ShulgaDmitry

2022-09-04 19:33 UTC, AlekseyQty requested changes
Нужно поправить 2 и 3 задание

2022-09-04 19:33 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_8/task_8_2.py
> +				print(f" Time work: {round(time.time(), 2)}")
Лучше сразу посчитай сколько работала функция в секундах, сейчас у тебя в выводе не очень репрезентативные данные:

 Time work: 1662319598.68
 Factorila: 6
 Time work: 1662319600.69

2022-09-04 19:33 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_8/task_8_3.py
> +        amount = int(amount)
Задание не совсем такое.

Нам нужно ввести числа, разделенные пробелами (например 1 2) и получить в результате эти же числа, только отсортированные в соответствии с их английскими названиями.

Т.е 1 = one, 2 = two выводим числа как 1 2, т.к one > two (o встречается раньше чем t в алфавите)

2022-09-06 16:09 UTC, ShulgaDmitry commented on shulga_dmitrij_vladimirovich/hm_8/task_8_3.py
> +        amount = int(amount)
Так у меня именно так и сортирует согласно алфавита, я просто на вход подаю рандомно выбранные числа согласно введенного количества чисел пользователем и затем сортирую их согласно лексикографического возрастания

2022-09-06 16:09 UTC, ShulgaDmitry commented on shulga_dmitrij_vladimirovich/hm_8/task_8_2.py
> +				print(f" Time work: {round(time.time(), 2)}")
Это подправил

2022-10-10 18:24 UTC, merged