homework_6
AlekseyQty/qap09-onl pull request #86
Opened 2022-08-16 13:22 UTC by Valery1995

Есть проблемка в task_6_2 : не выводится последняя буква строки, я уже сломал голову(

2022-08-22 09:24 UTC, AlekseyQty requested changes
Попробуй исправить баг во 2 задании

2022-08-22 09:24 UTC, AlekseyQty commented on aniskevich_valerij_francevich/hw_6/task_6_2.py
> +        if my_list[i - 1] == my_list[i]:
На первой итерации ты сравниваешь первый и последний элемент, видимо поэтому последний элемент и теряется:

my_list[-1] == my_list[0]

Лучше иди по списку слева направо, т.е сравнивай my_list[i] == my_list[i+1]

2022-08-22 09:24 UTC, AlekseyQty commented on aniskevich_valerij_francevich/hw_6/task_6_2.py
> +        if my_list[i - 1] == my_list[i]:
На первой итерации ты сравниваешь первый и последний элемент, видимо поэтому последний элемент и теряется:

my_list[-1] == my_list[0]

Лучше иди по списку слева направо, т.е сравнивай my_list[i] == my_list[i+1]

2022-08-26 20:34 UTC, Valery1995 commented on aniskevich_valerij_francevich/hw_6/task_6_2.py
> +        if my_list[i - 1] == my_list[i]:
Исправил!

2022-09-06 12:32 UTC, merged