Homework 9: Dmitry Shulga
AlekseyQty/qap09-onl pull request #99
Opened 2022-08-21 10:36 UTC by ShulgaDmitry

2022-09-06 10:08 UTC, AlekseyQty requested changes
Нужно отрефакторить первое задание и доделать второе

2022-09-06 10:08 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_9/task_9_1.py
> +status_reserved = ['Free', 'Free', 'Free']
Не стоит завязывать логику работу класса на внешний список.

2022-09-06 10:08 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_9/task_9_1.py
> +                self.reserved = reserved
Лучше воспринимай это пол как булеву переменную, т.е is_reserved = (True/False)

2022-09-06 10:08 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_9/task_9_1.py
> +                                print("You have already reserved this book")
Стоит убрать всю логику, связанную с захардкоженными названиями/параметрами книг.

Сейчас чтобы добавить одну книгу в твой класс придется менять логику всей программы.

Если хочешь работать со списком книг лучше реализуй еще один класс Library, в котором будет храниться список всех книг. И уже в своем классе работай с ним. Т.е чтобы показать список всех книг ты будешь просто вызывать соответсющий метод из нужного объекта класса Library (library.get_all_books)

2022-09-06 10:08 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_9/task_9_2.py
> +class Bank:
В задании нужно создать два класса: Bank,  Investment

2022-09-07 10:54 UTC, ShulgaDmitry commented on shulga_dmitrij_vladimirovich/hm_9/task_9_1.py
> +                self.reserved = reserved
Изменил на булеву переменную

2022-09-07 10:55 UTC, ShulgaDmitry commented on shulga_dmitrij_vladimirovich/hm_9/task_9_1.py
> +status_reserved = ['Free', 'Free', 'Free']
Список убрал

2022-09-07 10:55 UTC, ShulgaDmitry commented on shulga_dmitrij_vladimirovich/hm_9/task_9_1.py
> +                                print("You have already reserved this book")
Захаркоженность убрал, класс библиотеки не стал делать сложно было увязать с общей логикой

2022-09-07 10:56 UTC, ShulgaDmitry commented on shulga_dmitrij_vladimirovich/hm_9/task_9_2.py
> +class Bank:
Подправил

2022-09-07 10:56 UTC, ShulgaDmitry commented
Все скорректировал

2022-10-10 18:38 UTC, AlekseyQty commented on shulga_dmitrij_vladimirovich/hm_9/task_9_1.py
> +list_riders = {}
На будующее лучше не завязывай логику работы класса на внешние переменные. Делай так только в случае когда без этого совсем не обойтись.

Сейчас ты мог внести list_riders как переменную класса и проинициализировать ее в методе __init()__. Дальше ее можно было бы использовать как self.list_riders

2022-10-10 18:38 UTC, merged

2022-10-11 14:30 UTC, ShulgaDmitry commented on shulga_dmitrij_vladimirovich/hm_9/task_9_1.py
> +list_riders = {}
Я не особо понял как пустой словарь засунуть в переменную класса, можешь примерчик скинуть?

2022-10-11 14:50 UTC, ShulgaDmitry commented on shulga_dmitrij_vladimirovich/hm_9/task_9_1.py
> +list_riders = {}
Я вот так только смог верно ли?

`# Создайте класс book с именем книги, автором, кол-м страниц, ISBN, флагом, зарезервирована ли книги или нет.
# Создайте класс пользователь который может брать книгу, возвращать, бронировать. Если другой пользователь хочет взять
# зарезервированную книгу(или которую уже кто-то читает - надо ему про это сказать).

class Reader:

    def __init__(self, name_reader, number_book=None, list_riders=None):
        self.name_reader = name_reader
        self.number_book = number_book
        self.list_riders = list_riders

    def reader_choice(self, number_book):
        if number_book.is_reserved is True:
            if self.name_reader in self.list_riders.keys():
                for v in self.list_riders[self.name_reader]:
                    if v == number_book.name_book:
                        print("You have already reserved this book")
                        my_answer = input("You want to give it up: yes/no?: ")
                        if my_answer == "yes":
                            number_book.is_reserved = False
                            self.number_book = None
                            del self.list_riders[self.name_reader]
                            print("You want to cancel your booking")
            else:
                print("Sorry book was reserved")

        elif number_book.is_taken is True:
            if self.name_reader in self.list_riders.keys():
                for v in self.list_riders[self.name_reader]:
                    if v == number_book.name_book:
                        print("You have already reserved this book")
                        my_answer = input("You want to give it up: yes/no?: ")
                        if my_answer == "yes":
                            number_book.is_taken = False
                            self.number_book = None
                            del self.list_riders[self.name_reader]
                            print("You want to cancel your booking")
            else:
                print("Sorry book was taken")
                self.list_riders[self.name_reader] = [None, None, None]

        else:
            print("Choice what you want:")
            print("   a - I want take book")
            print("   b - I wan reserved book")

            status_book = input("Please select an action: ")

            if status_book == "a":
                number_book.is_taken = True
                print("You take this book")
                self.list_riders[self.name_reader] = [number_book.name_book, number_book.is_taken, number_book.is_reserved]

            elif status_book == "b":
                number_book.is_reserved = True
                print("You reserved this book")
                self.list_riders[self.name_reader] = [number_book.name_book, number_book.is_taken, number_book.is_reserved]

    @staticmethod
    def descriptive_reader(list_riders):
        reader_count = 0
        print("List of readers")
        for key, value in list_riders.items():
            reader_count += 1
            print(f"   {reader_count} - {key}; Name book: {value[0]}; Is taken: {value[1]}; "
                  f"Is reserved: {value[2]}")


class Book:

    book_count = 1

    def __init__(self, name_book, author, number_pages, isbn, is_reserved=False, is_taken=False):
        self.name_book = name_book
        self.author = author
        self.number_pages = number_pages
        self.isbn = isbn
        self.is_reserved = is_reserved
        self.is_taken = is_taken

    def descriptive_book(self):
        book_name = f"   {Book.book_count} - {self.name_book}; {self.author}; {self.number_pages}; {self.isbn}"
        Book.book_count += 1
        print(book_name)
        return book_name


print("Names books:")
my_new_book_1 = Book("Three Comrades", "Remarque Erich Maria", 480, "ISBN: 978-5-17-004252-4")
my_new_book_1.descriptive_book()
my_new_book_2 = Book("All Quiet on the Western Front", "Remarque Erich Maria", 200, "ISBN: 978-5-17-088940-2")
my_new_book_2.descriptive_book()
my_new_book_3 = Book("Heaven Has No Favorites", "Remarque Erich Maria", 288, "ISBN: 978-5-17-081140-3")
my_new_book_3.descriptive_book()

name = ""
list_riders = {}
while name != "quit":
    name = input("Please enter your namer and 'quit' if you want exit: ")
    if name == "quit":
        print("Goodbye")
        break
    else:

        my_book = input("Please select number book: ")
        my_book = int(my_book)
        my_reader = Reader(name, list_riders=list_riders)
        if my_book == 1:
            my_reader.reader_choice(my_new_book_1)
            my_reader.descriptive_reader(list_riders)
        elif my_book == 2:
            my_reader.reader_choice(my_new_book_2)
            my_reader.descriptive_reader(list_riders)
        elif my_book == 3:
            my_reader.reader_choice(my_new_book_3)
            my_reader.descriptive_reader(list_riders)`